# -*- coding: utf-8 -*-
"""example, line chart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnZ9JfSmGVevekiFtFcQgQG3gVMUIfIq
"""

import matplotlib.pyplot as plt
import numpy as np

ypoints = np.array([3, 8, 1, 10])

plt.plot(ypoints, marker = 'o', ms = 20, mec = 'r')
plt.show()