# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IX5sHkZ3ENq2MzgSe2U3AROOxVahxcEa
"""

import matplotlib.pyplot as plt
import numpy as np

xpoints = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
ypoints = np.array([211000, 183300, 224700, 222700, 209600, 201400, 295500, 361400, 234000, 266700, 412800, 300200])
plt.plot(xpoints, ypoints, linestyle='dotted', color='r')
plt.show()

xpoints = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
ypoints_facecream = np.array([2500, 2630, 2140, 3400, 3600, 2760, 2980, 3700, 3540, 1990, 2340, 2900])
ypoints_facewash = np.array([1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760])
ypoints_toothpaste = np.array([5200, 5100, 4550, 5870, 4560, 4890, 4780, 5860, 6100, 8300, 7300, 7400])
ypoints_bathingsoap = np.array([9200, 6100, 9550, 8870, 7760, 7490, 8980, 9960, 8100, 10300, 13300, 14400])
ypoints_shampoo = np.array([1200, 2100, 3550, 1870, 1560, 1890, 1780, 2860, 2100, 2300, 2400, 1800])
ypoints_moisturizer = np.array([1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760])

plt.plot(xpoints, ypoints_facecream, 'o')
plt.plot(xpoints, ypoints_facewash, 'o')
plt.plot(xpoints, ypoints_toothpaste, 'o')
plt.plot(xpoints, ypoints_bathingsoap, 'o')
plt.plot(xpoints, ypoints_shampoo, 'o')
plt.plot(xpoints, ypoints_moisturizer, 'o')
plt.show()

plt.plot(xpoints, ypoints_facecream, marker='o', ms=20, mec='r')
plt.plot(xpoints, ypoints_facewash, marker='o', ms=20, mec='r')
plt.show()

ypoints_total = np.array([21100, 18330, 22470, 22270, 20960, 20140, 29550, 36140, 23400, 26670, 41280, 30020])
plt.plot(ypoints_total, color='r', linewidth=20.5)
plt.show()